### PR TITLE
ANY23-291 Allow JSONLD scripts to be located anywhere in document

### PR DESCRIPTION
**Pull request by HansBrende**
Pretty self explanatory. Simply changed one xpath expression. Also added relevant tests.

mvn clean install -> all tests pass.

### CODE REVIEW

**Comment by ferrerod** [comment]
@HansBrende @lewismc: Today, I cloned master and tried to build: mvn clean install and the core build is failing. I also saw code commented out in the run method that would have written out the triples:

    for (JSONLDScript jsonldScript : jsonldScripts) {
      //String lang = documentLang;
      //if (jsonldScript.getLang() != null) {
      //        lang = jsonldScript.getLang();
      //}
      //out.writeTriple(documentIRI, jsonldScript.getName(),
      //                SimpleValueFactory.getInstance().createLiteral(jsonldScript.getContent(), lang));
    }

I currently don't see how the ExtractionResult out is being written to in the current master branch code for EmbeddedJSONLDExtractor.java

Thoughts?

[ERROR] Failures: 
[ERROR]   EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInBody:45->AbstractExtractorTestCase.assertModelNotEmpty:329 The model is expected to not be empty.Assertion failed! Extracted triples:

[ERROR]   EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHead:31->AbstractExtractorTestCase.assertModelNotEmpty:329 The model is expected to not be empty.Assertion failed! Extracted triples:

[ERROR]   EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHeadAndBody:52->AbstractExtractorTestCase.assertModelNotEmpty:329 The model is expected to not be empty.Assertion failed! Extracted triples:

[ERROR]   EmbeddedJSONLDExtractorTest.testSeveralEmbeddedJSONLDInHead:38->AbstractExtractorTestCase.assertModelNotEmpty:329 The model is expected to not be empty.Assertion failed! Extracted triples:

**Comment by lewismc** [comment]
Hi @ferrerod which Java version are you running?
Master build is stable
https://builds.apache.org/view/A/view/Any23/job/Any23-trunk/

**Comment by ferrerod** [comment]
java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by HansBrende** [comment]
@ferrerod I am unable to reproduce your error. Running `mvn clean install` on the master branch gives me:

```
[INFO] Apache Any23 ....................................... SUCCESS [  6.020 s]
[INFO] Apache Any23 :: Base API ........................... SUCCESS [  3.684 s]
[INFO] Apache Any23 :: Test Resources ..................... SUCCESS [  0.818 s]
[INFO] Apache Any23 :: CSV Utilities ...................... SUCCESS [  0.612 s]
[INFO] Apache Any23 :: Mime Type Detection ................ SUCCESS [  5.078 s]
[INFO] Apache Any23 :: Encoding Detection ................. SUCCESS [  1.730 s]
[INFO] Apache Any23 :: Core ............................... SUCCESS [ 39.300 s]
[INFO] Apache Any23 :: Plugins :: Office Scraper .......... SUCCESS [  7.402 s]
[INFO] Apache Any23 :: Plugins :: HTML Scraper ............ SUCCESS [  2.761 s]
[INFO] Apache Any23 :: CLI ................................ SUCCESS [ 23.814 s]
[INFO] Apache Any23 :: OpenIE ............................. SUCCESS [  2.224 s]
[INFO] Apache Any23 :: Plugins :: Basic Crawler ........... SUCCESS [ 38.897 s]
[INFO] Apache Any23 :: Plugins :: Integration Test ........ SUCCESS [01:18 min]
[INFO] Apache Any23 :: Service ............................ SUCCESS [ 32.645 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:03 min
[INFO] Finished at: 2018-02-09T14:35:24-06:00
[INFO] Final Memory: 79M/898M
```

**Comment by ferrerod** [comment]
do you guys have a slack channel so I don't clutter a closed PR with noise?

**Comment by ferrerod** [comment]
any chance your master isn't in sync with the one that's on github?

**Comment by HansBrende** [comment]
No chance. Diff is empty. @ferrerod try updating your Java version. 1.8.51 is pretty old.

**Comment by ferrerod** [comment]
Which version are you running? I see the latest 1.8 u161

**Comment by lewismc** [comment]
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by HansBrende** [comment]
And mine is:
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by ferrerod** [comment]
Java version seems to have been the culprit. Thank you.

**Comment by ferrerod** [comment]
My Java skills may be quite rusty, hence the 3 year old JDK. Looking at implementation of method run(.., Document in, ExtractionResult out) in `EmbeddedJSONLDExtractor.java`, I see a couple things that puzzle me and if you have time to explain I'd be grateful:

1. I do NOT see anywhere in EmbeddedJSONLDExtractor.java where 'out' is being written to. Why is that?

2. // the results of this method are never used?
`jsonldScripts = extractJSONLDScript(in, baseProfile, ..., out);`

3. //the inner class JSONLDScript takes 3 parameters in the initializer but only assigns xpath to an instance variable but the other two (IRI name, String content) are never assigned to the instance.  Is this intended / correct?

`    public JSONLDScript(String xpath, IRI name, String content) {
      this.xpath = xpath;
    }
`

**Comment by lewismc** [comment]
1. Look at the call to [extractJSONLDScript](https://github.com/apache/any23/blob/master/core/src/main/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractor.java#L81-L82) we use it further down. 
2. Yes this could probably be cleaned up, it is a bit messy right now.
3. Right now yes it is correct but I am not sure if it is the intended behavior. When i originally added the logic, it was what I wrote... if it does not make sense then please send a PR and we can clean it up.

For reference on extraction results, please see the following test files [html-embedded-jsonld-extractor-multiple.html
](https://github.com/apache/any23/blob/master/test-resources/src/test/resources/html/html-embedded-jsonld-extractor-multiple.html) and [html-embedded-jsonld-extractor.html
](https://github.com/apache/any23/blob/master/test-resources/src/test/resources/html/html-embedded-jsonld-extractor.html)

**Comment by ferrerod** [comment]
Thanks Lewis. 
1. I do see where extractJSONLDScript receives 'out' as a parameter, and within the for loop, passes out to another call to extractor.run(....,out), (as somewhat recursive use, except the extractor in this case is a new instance), however I am still not seeing 'out' being written to. I suspect it may not be necessary if the code is working as expected. 

I will have a deeper look at test files, etc. I see in

**Pull request merged**
