### PR TITLE
ANY23-297 Any23 doesn't build under JDK1.8

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses https://issues.apache.org/jira/browse/ANY23-297
@ansell can you please check how this affects your open pull request? Do you have any objections to merging this into master branch? Thanks

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @ansell any objections to merging into master branch? Seems the like the semargl issues are progressing which is great, however I don't think that should block us here in Any23. I'll commit by CoB today unless there are objections. Thanks

**Comment by ansell** [comment]
I will run a build to verify that it works and get back to you.

**Comment by lewismc** [comment]
Excellent Sir thank you :)

**Comment by lewismc** [comment]
Thank you @ansell

**Pull request merged**
