### PR TITLE
ANY23-329 fixed pom.xml version to 2.2-SNAPSHOT

### PR DESCRIPTION
**Pull request by ferrerod**
fix build by updating version to 2.2-SNAPSHOT to master pom.xml

### CODE REVIEW

**Comment by stain** [comment]
Thanks - these also seem to remain at `2.3-SNAPSHOT`:

```
stain@biggie:~/src/any23$ grep -r 2.3-SNAPSHOT .
./plugins/basic-crawler/pom.xml:      <version>2.3-SNAPSHOT</version>
./plugins/basic-crawler/pom.xml:      <version>2.3-SNAPSHOT</version>
./plugins/basic-crawler/pom.xml:      <version>2.3-SNAPSHOT</version>
./plugins/basic-crawler/pom.xml:      <version>2.3-SNAPSHOT</version>
./plugins/html-scraper/pom.xml:      <version>2.3-SNAPSHOT</version>
./plugins/office-scraper/pom.xml:      <version>2.3-SNAPSHOT</version>
```

**Comment by lewismc** [comment]
This will be fixed when I run a new release candidate folks. When we release 2.2 we will increment version to 2.3-SNAPSHOT

**Comment by ferrerod** [comment]
I changed the version to 2.2-SNAPSHOT in the pom.xml project root in order to successfully build the master branch. I thought master should always be buildable.

**Comment by lewismc** [comment]
I've pused these changes remotely @ferrerod 

> I thought master should always be buildable.

It should always be yes.

**Comment by ferrerod** [comment]
Thanks, I will have a look later today.

**Comment by ferrerod** [comment]
currently test testGZippedContent at core/src/test/java/org/apache/any23/Any23Test.java:312 is failing [ERROR]   Any23Test.testGZippedContent:312 » ConnectTimeout The host did not accept the ...

but this is happening on master and my branch. I will try again tomorrow.

**Comment by ferrerod** [comment]
everything looks good.

**Pull request closed without merging**
