### PR TITLE
Downloads page updates

### PR DESCRIPTION
**Pull request by band**
FIX ANY23-309 (spelling error)
FIX ANY23-306 (correct URLs for "WAR package with dependencies")

### CODE REVIEW

**Comment by lewismc** [comment]
+1 @band please merge into master and if possible please publish Website. If you need a hand please let me know. Thank you

**Comment by band** [comment]
@lewismc OK, but I do not see that I have way to merge the pull request. I think I should see a "Merge pull request" button or menu item, or a "Merge" drop-down menu. I am missing something here.

**Comment by lewismc** [comment]
@band the canonical source code for Any23 is available at https://git-wip-us.apache.org/repos/asf/any23.git as per [parent pom.xml specification](https://github.com/apache/any23/blob/master/pom.xml#L214-L219).
What you can do is merely add canonical source repository as ```origin``` and commit directly there. The Github mirror will then update and you will see the code change reflected here.

**Comment by afs** [comment]
To merge a github PR into the Apache codebase, you can add
```
[remote "github"]
	url = git@github.com:apache/any123.git
	fetch = +refs/heads/*:refs/remotes/github/*
```
to your local clone of the the Apache repo .git/config making `github` an upstream remote then do:
```
git pull github pull/NNN/head --no-ff
```
(or put the full "git@...." instead of "github" i believe)

The `--no-ff` means it will always put in a a merge commit and bringing up the editor. That gives you the chance to add a line "This closes #NNN." to the commit message which causes the github PR to be closed.

NNN is NN for a 2 digit PR.

**Comment by band** [comment]
@afs thanks for the how-to notes.
@lewismc: I actually fetched the canonical source (with the link you supplied) and it does not have the defects fixed by my PR. So I am confused about what code is where.
@lewismc: and both the core and cli modules do not build from source (for different reasons). So I am not sure what to do about that.

**Comment by lewismc** [comment]
@band 

> I actually fetched the canonical source (with the link you supplied) and it does not have the defects fixed by my PR. So I am confused about what code is where.

i can see it [here](https://git-wip-us.apache.org/repos/asf?p=any23.git;a=blob_plain;f=src/site/xdoc/download.xml.vm;hb=refs/heads/master) you can do the diff manually in any browser. You will see that the patch you've provided will fix some inconsistencies within that .xml document.

> and both the core and cli modules do not build from source (for different reasons). So I am not sure what to do about that.

Can you please post your Java, Maven versions along with the command you are using to build? Recently I was also having issues building master branch from source so we may have to do some work... I am unsure.
Thanks

**Comment by ansell** [comment]
@band Can you post the relevant build errors you are seeing after running maven using ``mvn -X -e clean install``

**Comment by band** [comment]
@ansell I posted the core build errors on issue ANY23-303 (both are remote context load errors). I will go back and post what I get with "mvn -X -e ..."

@lewismc I think I should open a new issue for the CLI build problem which results from a Failure not an Error. Let me know.

{code:Shell}
$ mvn -V
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T14:39:06-05:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"

$ mvn clean install
{code}

**Comment by band** [comment]
@lewismc I am stuck regarding how to proceed to commit the updated download.xml.vm file.
I do not have notes on how I even updated the pom.xml file with my name. So, please do provide some guidance on how to take what is in my github fork and get it into the git-wp-us.apache.org repo. I think it has to do with creating a branch with the JIRA issue number, but I need some exact steps to take.
(And I do regret that I did not keep notes of the steps I took then.)

**Comment by ansell** [comment]
Adding the repository that you can push to requires running the following (where you can name it something different to ``upstream``, you just need to reuse that name for when you push to it later on:

```git remote add upstream https://git-wip-us.apache.org/repos/asf/any23.git```

Then you can fetch that repository, just to get its branch/etc. information into your local copy using:

```git fetch upstream```

Or you can all fetch all remotes at the same time with:

```git fetch --all```

It is a recommendation to always branch when you are working on an issue. After you create the issue, you run the following to switch to master, update it to whatever is in the upstream, then start your branch:

```
git checkout master
git merge --ff-only upstream/master
git checkout -b ANY23-NNN
```

Then you commit on that branch and push it back to your github fork using:

```
git commit -a -m "Message goes here"
git push origin ANY23-NNN
```

Then open a pull request on Github so the others can review it.

Then if all is good and you are the one who will merge it back start by updating your master branch with any changes since you branched:

```
git fetch --all
git checkout master
git merge --ff-only upstream/master
```

Then merge the branch into master:

```
git merge --no-ff ANY23-NNN
```

And then push back to the upstream (which will require your Apache username and password):

```
git push upstream master
```

If this push fails with a message about a conflict because someone else pushed in the meantime (unlikely because you updated master just before merging and pushing, but still possible) then you need to run the following, note the difference this time to use ``--no-ff`` (no fast forward merging, so it will create a merge commit as you did above in 6a954ad):

```
git fetch --all
git merge --no-ff upstream/master
git push upstream master
```

HTH

**Pull request merged**
