### PR TITLE
ANY23-308 Adding option '-d' support for yaml file

### PR DESCRIPTION
**Pull request by jgrzebyta**
- Fix **ANY23-308**
  - Add unit test
  - Upadate `TikaMIMETypeDetector` class
  - Bring two utility classes into one module `apache-any23-utils`

### CODE REVIEW

**Comment by lewismc** [comment]
@jgrzebyta upon running the proposed tests I get the following
```
Running org.apache.any23.extractor.yaml.YAMLExtractorTest
[2017-06-20 13:00:10,613] INFO  5268[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
[2017-06-20 13:00:10,668] INFO  5323[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
[2017-06-20 13:00:10,674] INFO  5329[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
[2017-06-20 13:00:10,678] INFO  5333[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
[2017-06-20 13:00:10,682] INFO  5337[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
[2017-06-20 13:00:10,684] INFO  5339[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.073 sec - in org.apache.any23.extractor.yaml.YAMLExtractorTest
Running org.apache.any23.extractor.yaml.YAMLTikaParserTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in org.apache.any23.extractor.yaml.YAMLTikaParserTest
tikaDetect(org.apache.any23.extractor.yaml.YAMLTikaParserTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalArgumentException: Provided InputStream does not support marks
	at org.apache.any23.extractor.yaml.YAMLTikaParserTest.tikaDetect(YAMLTikaParserTest.java:41)

Running org.apache.any23.filter.ExtractionContextBlockerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.apache.any23.filter.ExtractionContextBlockerTest
Running org.apache.any23.filter.IgnoreAccidentalRDFaTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.apache.any23.filter.IgnoreAccidentalRDFaTest
Running org.apache.any23.http.AcceptHeaderBuilderTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.apache.any23.http.AcceptHeaderBuilderTest
Running org.apache.any23.plugin.Any23PluginManagerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.apache.any23.plugin.Any23PluginManagerTest
Running org.apache.any23.rdf.PrefixesTest
Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.apache.any23.rdf.PrefixesTest
Running org.apache.any23.rdf.RDFUtilsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.any23.rdf.RDFUtilsTest
Running org.apache.any23.SesameTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.any23.SesameTest
Running org.apache.any23.util.DiscoveryUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.49 sec - in org.apache.any23.util.DiscoveryUtilsTest
Running org.apache.any23.util.StringUtilsTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.apache.any23.util.StringUtilsTest
Running org.apache.any23.validator.DefaultValidatorTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.018 sec - in org.apache.any23.validator.DefaultValidatorTest
Running org.apache.any23.validator.XMLValidationReportSerializerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in org.apache.any23.validator.XMLValidationReportSerializerTest
Running org.apache.any23.vocab.RDFSchemaUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 sec - in org.apache.any23.vocab.RDFSchemaUtilsTest
Running org.apache.any23.vocab.VocabularyTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.apache.any23.vocab.VocabularyTest
Running org.apache.any23.writer.JSONWriterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.any23.writer.JSONWriterTest
Running org.apache.any23.writer.WriterRegistryTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in org.apache.any23.writer.WriterRegistryTest

Results :

Tests in error:
  EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHead:30->AbstractExtractorTestCase.assertExtract:223->AbstractExtractorTestCase.assertExtract:210 » Runtime
  EmbeddedJSONLDExtractorTest.testSeveralEmbeddedJSONLDInHead:37->AbstractExtractorTestCase.assertExtract:223->AbstractExtractorTestCase.assertExtract:210 » Runtime
  YAMLTikaParserTest.tikaDetect:41 » IllegalArgument Provided InputStream does n...

Tests run: 394, Failures: 0, Errors: 3, Skipped: 15

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache Any23 ....................................... SUCCESS [ 19.568 s]
[INFO] Apache Any23 :: Base API ........................... SUCCESS [  4.437 s]
[INFO] Apache Any23 :: Test Resources ..................... SUCCESS [  0.327 s]
[INFO] Apache Any23 :: Utilities .......................... SUCCESS [  2.754 s]
[INFO] Apache Any23 :: Mime Type Detection ................ SUCCESS [01:51 min]
[INFO] Apache Any23 :: Encoding Detection ................. SUCCESS [  0.987 s]
[INFO] Apache Any23 :: Core ............................... FAILURE [ 37.718 s]
[INFO] Apache Any23 :: CLI ................................ SKIPPED
[INFO] Apache Any23 :: Plugins :: Basic Crawler ........... SKIPPED
[INFO] Apache Any23 :: Plugins :: HTML Scraper ............ SKIPPED
[INFO] Apache Any23 :: Plugins :: Office Scraper .......... SKIPPED
[INFO] Apache Any23 :: Plugins :: Integration Test ........ SKIPPED
[INFO] Apache Any23 :: Service ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:57 min
[INFO] Finished at: 2017-06-20T13:00:11-07:00
[INFO] Final Memory: 52M/455M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project apache-any23-core: There are test failures.
[ERROR]
[ERROR] Please refer to /usr/local/any23/core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apache-any23-core
```

**Comment by jgrzebyta** [comment]
@lewismc What is your command line for test? When I use `mvn clean test` I cannot reproduce the error.

For the particular test my output is:
```
cd /home/jacek/NetBeansProjects/any23/core; JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 M2_HOME=/home/jacek/opt/apache-maven-3.3.9 /home/jacek/opt/apache-maven-3.3.9/bin/mvn -Dtest=org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest surefire:test
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Apache Any23 :: Core 2.1-SNAPSHOT
------------------------------------------------------------------------

--- maven-surefire-plugin:2.19.1:test (default-cli) @ apache-any23-core ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest
[2017-06-20 22:15:45,403] INFO     0[main] - org.apache.any23.rdf.PopularPrefixes.getPrefixes(PopularPrefixes.java:45) - Loading prefixes from /org/apache/any23/prefixes/prefixes.properties
[2017-06-20 22:15:45,419] INFO    16[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
[2017-06-20 22:15:59,387] INFO 13984[main] - org.apache.any23.extractor.SingleDocumentExtraction.run(SingleDocumentExtraction.java:220) - Processing http://bob.example.com/
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.969 sec - in org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 19.251 s
Finished at: 2017-06-20T22:16:01+01:00
Final Memory: 15M/303M
------------------------------------------------------------------------

```

**Comment by lewismc** [comment]
Hi @jgrzebyta this is when I attempt build the source project from top level directory
```
$ mvn clean test
...
Results :

Tests in error:
  EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHead:30->AbstractExtractorTestCase.assertExtract:223->AbstractExtractorTestCase.assertExtract:210 » Runtime
  EmbeddedJSONLDExtractorTest.testSeveralEmbeddedJSONLDInHead:37->AbstractExtractorTestCase.assertExtract:223->AbstractExtractorTestCase.assertExtract:210 » Runtime

Tests run: 394, Failures: 0, Errors: 2, Skipped: 15

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache Any23 ....................................... SUCCESS [  0.792 s]
[INFO] Apache Any23 :: Base API ........................... SUCCESS [  1.575 s]
[INFO] Apache Any23 :: Test Resources ..................... SUCCESS [  0.191 s]
[INFO] Apache Any23 :: Utilities .......................... SUCCESS [  1.018 s]
[INFO] Apache Any23 :: Mime Type Detection ................ SUCCESS [  2.081 s]
[INFO] Apache Any23 :: Encoding Detection ................. SUCCESS [  0.883 s]
[INFO] Apache Any23 :: Core ............................... FAILURE [  8.565 s]
[INFO] Apache Any23 :: CLI ................................ SKIPPED
[INFO] Apache Any23 :: Plugins :: Basic Crawler ........... SKIPPED
[INFO] Apache Any23 :: Plugins :: HTML Scraper ............ SKIPPED
[INFO] Apache Any23 :: Plugins :: Office Scraper .......... SKIPPED
[INFO] Apache Any23 :: Plugins :: Integration Test ........ SKIPPED
[INFO] Apache Any23 :: Service ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
The test results are as follows
```
-------------------------------------------------------------------------------
Test set: org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.524 sec <<< FAILURE! - in org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest
testEmbeddedJSONLDInHead(org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest)  Time elapsed: 1.141 sec  <<< ERROR!
java.lang.RuntimeException: org.apache.any23.extractor.ExtractionException: Error while parsing RDF document.
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:30)
Caused by: org.apache.any23.extractor.ExtractionException: Error while parsing RDF document.
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:30)
Caused by: org.eclipse.rdf4j.rio.RDFParseException: Could not parse JSONLD
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:30)
Caused by: com.github.jsonldjava.core.JsonLdError: loading remote context failed: http://json-ld.org/contexts/person.jsonld
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:30)

testSeveralEmbeddedJSONLDInHead(org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest)  Time elapsed: 0.383 sec  <<< ERROR!
java.lang.RuntimeException: org.apache.any23.extractor.ExtractionException: Error while parsing RDF document.
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testSeveralEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:37)
Caused by: org.apache.any23.extractor.ExtractionException: Error while parsing RDF document.
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testSeveralEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:37)
Caused by: org.eclipse.rdf4j.rio.RDFParseException: Could not parse JSONLD
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testSeveralEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:37)
Caused by: com.github.jsonldjava.core.JsonLdError: loading remote context failed: http://json-ld.org/contexts/person.jsonld
	at org.apache.any23.extractor.html.EmbeddedJSONLDExtractorTest.testSeveralEmbeddedJSONLDInHead(EmbeddedJSONLDExtractorTest.java:37)
```

**Comment by lewismc** [comment]
@ansell are you able to fetch this pull request and test it locally? I am still getting the failures as above.

**Comment by jgrzebyta** [comment]
@lewismc  @ansell 
In ANY23-306 I have created travis support. It will process testing as well. If you do not mind let's wait until that will be accepted. Than I will merge that new feature into this PR.

**Comment by lewismc** [comment]
@jgrzebyta this is now in conflict

**Comment by ansell** [comment]
Hi @jgrzebyta , you have far too many white-space changes across this pull request to merge it. Can you extract the lines that have meaningful changes onto a new branch and submit a new pull request?

@lewismc Can you download https://github.com/jsonld-java/jsonld-java from git and run its tests to see whether you are also having issues with them? It is likely a network issue at your end, as those tests are still succeeding on master for me, but it would be useful to see whether the broader jsonld testsuite is also failing for your machine.

**Comment by lewismc** [comment]
ack @ansell I downloaded the jsonld-java source and upon building I get the following
```
[ERROR] Errors:
[ERROR]   DocumentLoaderTest.fromURLCache:169 » SSLHandshake sun.security.validator.Vali...
[ERROR]   DocumentLoaderTest.testDisallowRemoteContexts:344 » JsonLd loading remote cont...
[ERROR]   LocalBaseTest.testMixedLocalRemoteBaseLocalContextFirst:47 » JsonLd loading re...
[ERROR]   LocalBaseTest.testMixedLocalRemoteBaseRemoteContextFirst:26 » JsonLd loading r...
[INFO]
[ERROR] Tests run: 555, Failures: 0, Errors: 4, Skipped: 9
```

**Comment by ansell** [comment]
Can you get the full stacktraces for those errors, in particular the SSLHandshake that I haven't seen fail before.

**Comment by ansell** [comment]
Also, are you able to download ``http://json-ld.org/contexts/person.jsonld`` successfully in all of your browsers and on the command line using ``wget`` and ``curl``?

**Comment by ansell** [comment]
The key may be the TLS certificate used by json-ld.org, as that HTTP URL redirects to an HTTPS URL. If you are using a Java version that doesn't have TLS SNI (Server Name Indication) enabled (or has a bug in its SNI process), you will get an expired certificate according to ssllabs.com:

https://www.ssllabs.com/ssltest/analyze.html?d=json%2dld.org&latest

What is your java version?

**Comment by ansell** [comment]
I filed it as an issue with the maintainers of json-ld.org: https://github.com/json-ld/json-ld.org/issues/519

**Comment by ansell** [comment]
They are not able to change the default host to point to json-ld.org as they are hosting other websites together. Best guess right now for you is to update your java version (assuming you don't have a TLS proxy on your site that is failing when it sees the expired Traefik default certificate, which SNI should route around silently if the certificates all make their way successfully to your JDK). I thought all Java-8 releases supported SNI, and we are already requiring JDK-8 for this project.

**Comment by davidlehn** [comment]
It looks like that test suite is depending on the json-ld.org person context URL?  It might be best not to depend on that in the first place.  I doubt anyone knew those URLs were being used like that so it's possible they might just move, change, or disappear at some point.

**Comment by ansell** [comment]
Sorry, I wasn't aware that they were temporary contexts, the person one has been around without change for 5 years now https://github.com/json-ld/json-ld.org/tree/master/contexts . Any23 (and JSONLD-Java) both try to test with live URLs to verify that real websites can communicate with them, so we aren't fooled into thinking that we can communicate properly just based on some mocked up local websites. If you have any more authoritative static URLs it would be great. 

We have had a lot of issues communicating specifically with schema.org over the years, so we try not to solely use it as a reference, hence the inclusion of the static json-ld.org URLs.

**Comment by davidlehn** [comment]
If not for this SNI issue I'd just keep using those URLs until they break. ;-)  As you say, we haven't touched them in 5 years.  It might be a nice idea to have explicit test URLs on the json-ld.org site in order to do remote tests like this.  If you have ideas on that feel free to file an issue or PR.

**Comment by ansell** [comment]
I don't mind if it breaks because they are moved, then it would break for everyone. The SNI issues were just annoying when we didn't know what the cause was, they should be able to be worked around, unless it turns out there is a TLS proxy where @lewismc works (NASA=government, so anything is possible). 

They are non-specific functional tests that we can replace easily if there are alternatives. I will open an issue to add formalised test context/sample JSON-LD resources to json-ld.org, to track it for future.

**Comment by lewismc** [comment]
@ansell sure thing
```
-------------------------------------------------------------------------------
Test set: com.github.jsonldjava.core.LocalBaseTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 30.048 s <<< FAILURE! - in com.github.jsonldjava.core.LocalBaseTest
testMixedLocalRemoteBaseLocalContextFirst(com.github.jsonldjava.core.LocalBaseTest)  Time elapsed: 30.045 s  <<< ERROR!
com.github.jsonldjava.core.JsonLdError: loading remote context failed: https://raw.githubusercontent.com/monarch-initiative/monarch-app/master/conf/monarch-context.jsonld
	at com.github.jsonldjava.core.LocalBaseTest.testMixedLocalRemoteBaseLocalContextFirst(LocalBaseTest.java:47)
Caused by: java.net.UnknownHostException: raw.githubusercontent.com: unknown error
	at com.github.jsonldjava.core.LocalBaseTest.testMixedLocalRemoteBaseLocalContextFirst(LocalBaseTest.java:47)

testMixedLocalRemoteBaseRemoteContextFirst(com.github.jsonldjava.core.LocalBaseTest)  Time elapsed: 0.003 s  <<< ERROR!
com.github.jsonldjava.core.JsonLdError: loading remote context failed: https://raw.githubusercontent.com/monarch-initiative/monarch-app/master/conf/monarch-context.jsonld
	at com.github.jsonldjava.core.LocalBaseTest.testMixedLocalRemoteBaseRemoteContextFirst(LocalBaseTest.java:26)
Caused by: java.net.UnknownHostException: raw.githubusercontent.com
	at com.github.jsonldjava.core.LocalBaseTest.testMixedLocalRemoteBaseRemoteContextFirst(LocalBaseTest.java:26)
```

```
-------------------------------------------------------------------------------
Test set: com.github.jsonldjava.core.DocumentLoaderTest
-------------------------------------------------------------------------------
Tests run: 19, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 24.809 s <<< FAILURE! - in com.github.jsonldjava.core.DocumentLoaderTest
testDisallowRemoteContexts(com.github.jsonldjava.core.DocumentLoaderTest)  Time elapsed: 5.557 s  <<< ERROR!
com.github.jsonldjava.core.JsonLdError: loading remote context failed: http://json-ld.org/contexts/person.jsonld
	at com.github.jsonldjava.core.DocumentLoaderTest.testDisallowRemoteContexts(DocumentLoaderTest.java:344)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.github.jsonldjava.core.DocumentLoaderTest.testDisallowRemoteContexts(DocumentLoaderTest.java:344)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.github.jsonldjava.core.DocumentLoaderTest.testDisallowRemoteContexts(DocumentLoaderTest.java:344)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.github.jsonldjava.core.DocumentLoaderTest.testDisallowRemoteContexts(DocumentLoaderTest.java:344)

fromURLCache(com.github.jsonldjava.core.DocumentLoaderTest)  Time elapsed: 0.38 s  <<< ERROR!
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.github.jsonldjava.core.DocumentLoaderTest.fromURLCache(DocumentLoaderTest.java:169)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.github.jsonldjava.core.DocumentLoaderTest.fromURLCache(DocumentLoaderTest.java:169)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.github.jsonldjava.core.DocumentLoaderTest.fromURLCache(DocumentLoaderTest.java:169)
```

**Comment by jgrzebyta** [comment]
Refreshed code will go to new PR

**Comment by ansell** [comment]
@lewismc You are having DNS issues if you cannot resolve raw.githubusercontent.com (and not clear how you can even be using Github in that case). Contact your network administrator to sort that out.

The certificate issues for json-ld.org look like you are having issues with TLS SNI as discussed above.

The output of ``java -version`` and ``mvn -version`` should help clear up whether you are running the latest JDK build and if not, you need to update to it before developing further.

**Comment by lewismc** [comment]
ack @ansell I upgraded and all tests are passing fine, I was using Oracle JDK 1.8.0_99, have not upgraded to 1.8.0_131 and all tests pass. Thanks.

**Pull request closed without merging**
