### PR TITLE
ANY23-393 Any23 master to build under JDK 10.X

### PR DESCRIPTION
**Pull request by lewismc**
Issue addresses build under following environment
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T11:33:14-07:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 10.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "Mac"
```

### CODE REVIEW

**Comment by HansBrende** [comment]
@lewismc  +1. Just out of curiosity, what is the new `javax.xml.bind:jaxb-api` dependency for?

**Comment by lewismc** [comment]
@HansBrende thanks for review, from what I remember, this is not packaged with Tomcat9 anymore, which is what users should be using to deploy the Any23 WAR.

**Comment by jgrzebyta** [comment]
@lewismc  What about java-8? Will java-10 binary be the official one?

**Comment by lewismc** [comment]
@jgrzebyta good question. 
I previously used JDK 8 and Any23 was building absolutely fine. I experienced no issues. 
When I upgraded, the issues started... hence this PR.

**Comment by jgrzebyta** [comment]
@lewismc  Thanks. For me it's ok.

**Pull request merged**
